//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedVinc.WEB.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SiteLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeedVinc.WEB.UI.Resources.SiteLanguage", typeof(SiteLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string About_Us {
            get {
                return ResourceManager.GetString("About_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and accept the agreement.
        /// </summary>
        public static string Accept_Agreement {
            get {
                return ResourceManager.GetString("Accept_Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string Account_Settings {
            get {
                return ResourceManager.GetString("Account_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Time.
        /// </summary>
        public static string Active_Time {
            get {
                return ResourceManager.GetString("Active_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active User.
        /// </summary>
        public static string Active_User {
            get {
                return ResourceManager.GetString("Active_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Admin.
        /// </summary>
        public static string Add_Admin {
            get {
                return ResourceManager.GetString("Add_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Campaign.
        /// </summary>
        public static string Add_Campaign {
            get {
                return ResourceManager.GetString("Add_Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Character.
        /// </summary>
        public static string Add_Character {
            get {
                return ResourceManager.GetString("Add_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Event.
        /// </summary>
        public static string Add_Event {
            get {
                return ResourceManager.GetString("Add_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Feedback.
        /// </summary>
        public static string Add_Feedback {
            get {
                return ResourceManager.GetString("Add_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add member.
        /// </summary>
        public static string Add_Member {
            get {
                return ResourceManager.GetString("Add_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Video.
        /// </summary>
        public static string Add_Video {
            get {
                return ResourceManager.GetString("Add_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads.
        /// </summary>
        public static string Ads {
            get {
                return ResourceManager.GetString("Ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advert Time.
        /// </summary>
        public static string Advert_Time {
            get {
                return ResourceManager.GetString("Advert_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising Days.
        /// </summary>
        public static string Advertising_Days {
            get {
                return ResourceManager.GetString("Advertising_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adverts Campaign.
        /// </summary>
        public static string Adverts_Campaign {
            get {
                return ResourceManager.GetString("Adverts_Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggrement.
        /// </summary>
        public static string Aggrement {
            get {
                return ResourceManager.GetString("Aggrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please answer these questions bellow.
        /// </summary>
        public static string Answer_Questions {
            get {
                return ResourceManager.GetString("Answer_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appointment with other people.
        /// </summary>
        public static string appointment_with_other_people {
            get {
                return ResourceManager.GetString("appointment_with_other_people", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Around Me.
        /// </summary>
        public static string Around_Me {
            get {
                return ResourceManager.GetString("Around_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give avatar a name.
        /// </summary>
        public static string AvatarName {
            get {
                return ResourceManager.GetString("AvatarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing address.
        /// </summary>
        public static string Billing_Address {
            get {
                return ResourceManager.GetString("Billing_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast Range.
        /// </summary>
        public static string Broadcast_Range {
            get {
                return ResourceManager.GetString("Broadcast_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        public static string Campaign {
            get {
                return ResourceManager.GetString("Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Owner.
        /// </summary>
        public static string Card_Owner {
            get {
                return ResourceManager.GetString("Card_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carts.
        /// </summary>
        public static string Carts {
            get {
                return ResourceManager.GetString("Carts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Flow Rate.
        /// </summary>
        public static string Cash_Flow_Rate {
            get {
                return ResourceManager.GetString("Cash_Flow_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Analyses.
        /// </summary>
        public static string Character_Analyses {
            get {
                return ResourceManager.GetString("Character_Analyses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Criterion.
        /// </summary>
        public static string Choose_Criterion {
            get {
                return ResourceManager.GetString("Choose_Criterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Video.
        /// </summary>
        public static string Choose_Video {
            get {
                return ResourceManager.GetString("Choose_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen Video.
        /// </summary>
        public static string Chosen_Video {
            get {
                return ResourceManager.GetString("Chosen_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communities.
        /// </summary>
        public static string Communities {
            get {
                return ResourceManager.GetString("Communities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Owner.
        /// </summary>
        public static string Community_Owner {
            get {
                return ResourceManager.GetString("Community_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitor analysis.
        /// </summary>
        public static string Competitor_Analysis {
            get {
                return ResourceManager.GetString("Competitor_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        public static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacted People.
        /// </summary>
        public static string Contacted_People {
            get {
                return ResourceManager.GetString("Contacted_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuing Campaigns.
        /// </summary>
        public static string Continuing_Campaigns {
            get {
                return ResourceManager.GetString("Continuing_Campaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuing meeting.
        /// </summary>
        public static string Continuing_Meeting {
            get {
                return ResourceManager.GetString("Continuing_Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion-Rate.
        /// </summary>
        public static string Conversion_Rate {
            get {
                return ResourceManager.GetString("Conversion_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All right reserved FeedVinc © 2016.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        public static string Credit_Card {
            get {
                return ResourceManager.GetString("Credit_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Information.
        /// </summary>
        public static string Credit_Card_Information {
            get {
                return ResourceManager.GetString("Credit_Card_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card No.
        /// </summary>
        public static string Credit_Card_No {
            get {
                return ResourceManager.GetString("Credit_Card_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Project.
        /// </summary>
        public static string Current_Project {
            get {
                return ResourceManager.GetString("Current_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer of Cost.
        /// </summary>
        public static string Customer_of_Cost {
            get {
                return ResourceManager.GetString("Customer_of_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers Segment.
        /// </summary>
        public static string Customers_Segment {
            get {
                return ResourceManager.GetString("Customers_Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Budget.
        /// </summary>
        public static string Daily_Budget {
            get {
                return ResourceManager.GetString("Daily_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description ( Max 500 Characters).
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joın as Developer!.
        /// </summary>
        public static string Developer_Button {
            get {
                return ResourceManager.GetString("Developer_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make deal with financiers &amp; entrepreneurs for software bussiness or design bussiness ! .
        /// </summary>
        public static string Developer_Slogan {
            get {
                return ResourceManager.GetString("Developer_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers.
        /// </summary>
        public static string Developers {
            get {
                return ResourceManager.GetString("Developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Report.
        /// </summary>
        public static string Digital_Report {
            get {
                return ResourceManager.GetString("Digital_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directed to link.
        /// </summary>
        public static string Directed_Link {
            get {
                return ResourceManager.GetString("Directed_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to download the user-mails.
        /// </summary>
        public static string Download_User_Mails {
            get {
                return ResourceManager.GetString("Download_User_Mails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Admin.
        /// </summary>
        public static string Edit_Admin {
            get {
                return ResourceManager.GetString("Edit_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Pictures.
        /// </summary>
        public static string Edit_Pictures {
            get {
                return ResourceManager.GetString("Edit_Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profil.
        /// </summary>
        public static string Edit_Profil {
            get {
                return ResourceManager.GetString("Edit_Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project.
        /// </summary>
        public static string Edit_Project {
            get {
                return ResourceManager.GetString("Edit_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Society.
        /// </summary>
        public static string Edit_Society {
            get {
                return ResourceManager.GetString("Edit_Society", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Team.
        /// </summary>
        public static string Edit_Team {
            get {
                return ResourceManager.GetString("Edit_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational status.
        /// </summary>
        public static string Educational_Status {
            get {
                return ResourceManager.GetString("Educational_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Settings.
        /// </summary>
        public static string Email_Settings {
            get {
                return ResourceManager.GetString("Email_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must contains @ sembols !.
        /// </summary>
        public static string EmailAddess_Validation {
            get {
                return ResourceManager.GetString("EmailAddess_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        public static string EmailUnique_Validation {
            get {
                return ResourceManager.GetString("EmailUnique_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrepreneur.
        /// </summary>
        public static string Entrepreneur {
            get {
                return ResourceManager.GetString("Entrepreneur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joın as Entrepreneur!.
        /// </summary>
        public static string Entrepreneur_Button {
            get {
                return ResourceManager.GetString("Entrepreneur_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact developers &amp; financiers  make your idea!.
        /// </summary>
        public static string Entrepreneur_Slogan {
            get {
                return ResourceManager.GetString("Entrepreneur_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrepreneurs.
        /// </summary>
        public static string Entrepreneurs {
            get {
                return ResourceManager.GetString("Entrepreneurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimates/Goals.
        /// </summary>
        public static string Estimates_Goals {
            get {
                return ResourceManager.GetString("Estimates_Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses / Incoming.
        /// </summary>
        public static string Expenses_Incoming {
            get {
                return ResourceManager.GetString("Expenses_Incoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert in.
        /// </summary>
        public static string Expert_In {
            get {
                return ResourceManager.GetString("Expert_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        public static string Expiration_Date {
            get {
                return ResourceManager.GetString("Expiration_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation.
        /// </summary>
        public static string Explanation {
            get {
                return ResourceManager.GetString("Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Points.
        /// </summary>
        public static string Feed_Points {
            get {
                return ResourceManager.GetString("Feed_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedvinc come together all informatics ecosystem!.
        /// </summary>
        public static string Feedvinc_Slogan {
            get {
                return ResourceManager.GetString("Feedvinc_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Leverage Ratio.
        /// </summary>
        public static string Financial_leverage_ratio {
            get {
                return ResourceManager.GetString("Financial_leverage_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Report Request.
        /// </summary>
        public static string Financial_Report_Request {
            get {
                return ResourceManager.GetString("Financial_Report_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Status.
        /// </summary>
        public static string Financial_Status {
            get {
                return ResourceManager.GetString("Financial_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financier.
        /// </summary>
        public static string Financier {
            get {
                return ResourceManager.GetString("Financier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joın as fınancıer!.
        /// </summary>
        public static string Financier_Button {
            get {
                return ResourceManager.GetString("Financier_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invest the company&apos;s future today! .
        /// </summary>
        public static string Financier_Slogan {
            get {
                return ResourceManager.GetString("Financier_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financiers.
        /// </summary>
        public static string Financiers {
            get {
                return ResourceManager.GetString("Financiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        public static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        public static string Forget_Password {
            get {
                return ResourceManager.GetString("Forget_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field!.
        /// </summary>
        public static string FullName_Validation {
            get {
                return ResourceManager.GetString("FullName_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get an Appointment.
        /// </summary>
        public static string Get_an_appointment {
            get {
                return ResourceManager.GetString("Get_an_appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give appointment.
        /// </summary>
        public static string Give_Appointment {
            get {
                return ResourceManager.GetString("Give_Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        public static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth.
        /// </summary>
        public static string Growth {
            get {
                return ResourceManager.GetString("Growth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still member? Giriş Yapın.
        /// </summary>
        public static string Has_Account_Login {
            get {
                return ResourceManager.GetString("Has_Account_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Comment your Post.
        /// </summary>
        public static string Has_comment_your_Post {
            get {
                return ResourceManager.GetString("Has_comment_your_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has not account? Sign Up.
        /// </summary>
        public static string Has_Not_Account {
            get {
                return ResourceManager.GetString("Has_Not_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Tagged you.
        /// </summary>
        public static string Has_tagged_you {
            get {
                return ResourceManager.GetString("Has_tagged_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Email.
        /// </summary>
        public static string Hide_Email {
            get {
                return ResourceManager.GetString("Hide_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobies.
        /// </summary>
        public static string Hobies {
            get {
                return ResourceManager.GetString("Hobies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idea development.
        /// </summary>
        public static string Idea_Development {
            get {
                return ResourceManager.GetString("Idea_Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming Report Requests.
        /// </summary>
        public static string Incoming_Report_Requests {
            get {
                return ResourceManager.GetString("Incoming_Report_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some informations will be given to
        ///the investor as Investment report only
        ///and only if a project leader gives
        ///permission.
        /// </summary>
        public static string Info_Mission {
            get {
                return ResourceManager.GetString("Info_Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The informations of your project that
        ///you give will be kept under data
        ///privacy and will not be shared
        ///without your permission..
        /// </summary>
        public static string Info_Project {
            get {
                return ResourceManager.GetString("Info_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction.
        /// </summary>
        public static string Interaction {
            get {
                return ResourceManager.GetString("Interaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment.
        /// </summary>
        public static string Investment {
            get {
                return ResourceManager.GetString("Investment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment expectation.
        /// </summary>
        public static string Investment_Expectation {
            get {
                return ResourceManager.GetString("Investment_Expectation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment letter.
        /// </summary>
        public static string Investment_Letter {
            get {
                return ResourceManager.GetString("Investment_Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Status.
        /// </summary>
        public static string Investment_Status {
            get {
                return ResourceManager.GetString("Investment_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined.
        /// </summary>
        public static string Joined {
            get {
                return ResourceManager.GetString("Joined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string Learn_More {
            get {
                return ResourceManager.GetString("Learn_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liked your Post.
        /// </summary>
        public static string Liked_your_Post {
            get {
                return ResourceManager.GetString("Liked_your_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Password is wrong !.
        /// </summary>
        public static string Login_Error {
            get {
                return ResourceManager.GetString("Login_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look All.
        /// </summary>
        public static string Look_All {
            get {
                return ResourceManager.GetString("Look_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        public static string Marital_Status {
            get {
                return ResourceManager.GetString("Marital_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        public static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market potential.
        /// </summary>
        public static string Market_Potential {
            get {
                return ResourceManager.GetString("Market_Potential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market/Scaling.
        /// </summary>
        public static string Market_Scaling {
            get {
                return ResourceManager.GetString("Market_Scaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Value.
        /// </summary>
        public static string Market_Value {
            get {
                return ResourceManager.GetString("Market_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting request.
        /// </summary>
        public static string Meeting_Request {
            get {
                return ResourceManager.GetString("Meeting_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting requests.
        /// </summary>
        public static string Meeting_Requests {
            get {
                return ResourceManager.GetString("Meeting_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetings in future.
        /// </summary>
        public static string Meetings_Future {
            get {
                return ResourceManager.GetString("Meetings_Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor meetings.
        /// </summary>
        public static string Mentor_Meetings {
            get {
                return ResourceManager.GetString("Mentor_Meetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics Report.
        /// </summary>
        public static string Metrics_Report {
            get {
                return ResourceManager.GetString("Metrics_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “Missions” is a virtual incubation
        ///center that guides entrepreneurs. İt
        ///shows the key Points of your project
        ///for better and faster entry to the
        ///market.
        /// </summary>
        public static string Mission_Description {
            get {
                return ResourceManager.GetString("Mission_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missions.
        /// </summary>
        public static string Missions {
            get {
                return ResourceManager.GetString("Missions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Downloads.
        /// </summary>
        public static string Mobile_Downloads {
            get {
                return ResourceManager.GetString("Mobile_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile User.
        /// </summary>
        public static string Mobile_User {
            get {
                return ResourceManager.GetString("Mobile_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthy Directed.
        /// </summary>
        public static string Monthy_Directed {
            get {
                return ResourceManager.GetString("Monthy_Directed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Projects.
        /// </summary>
        public static string My_Projects {
            get {
                return ResourceManager.GetString("My_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News feed.
        /// </summary>
        public static string News_Feed {
            get {
                return ResourceManager.GetString("News_Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Project.
        /// </summary>
        public static string Next_Project {
            get {
                return ResourceManager.GetString("Next_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No chosen Video.
        /// </summary>
        public static string No_chosen_Video {
            get {
                return ResourceManager.GetString("No_chosen_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        public static string Not_Available {
            get {
                return ResourceManager.GetString("Not_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User wants notifications from this
        ///Project.
        /// </summary>
        public static string Notifications_this_Project {
            get {
                return ResourceManager.GetString("Notifications_this_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of visitors.
        /// </summary>
        public static string Number_Visitors {
            get {
                return ResourceManager.GetString("Number_Visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okey.
        /// </summary>
        public static string Okey {
            get {
                return ResourceManager.GetString("Okey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-time budgetary.
        /// </summary>
        public static string One_time_Budgetary {
            get {
                return ResourceManager.GetString("One_time_Budgetary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Confirmed.
        /// </summary>
        public static string Order_Confirmed {
            get {
                return ResourceManager.GetString("Order_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize a Meeting.
        /// </summary>
        public static string Organize_Meeting {
            get {
                return ResourceManager.GetString("Organize_Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Again.
        /// </summary>
        public static string Password_Again {
            get {
                return ResourceManager.GetString("Password_Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match !.
        /// </summary>
        public static string Password_ConfirmValidation {
            get {
                return ResourceManager.GetString("Password_ConfirmValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contains one lowercase characters, one uppercase, one digit and one sembols like ($#) and Password Length must be 8 chars or more.
        /// </summary>
        public static string Password_Validation {
            get {
                return ResourceManager.GetString("Password_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Campaigns.
        /// </summary>
        public static string Past_Campaigns {
            get {
                return ResourceManager.GetString("Past_Campaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past meetings.
        /// </summary>
        public static string Past_Meetings {
            get {
                return ResourceManager.GetString("Past_Meetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Information.
        /// </summary>
        public static string Payment_Information {
            get {
                return ResourceManager.GetString("Payment_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write the email you want to add.
        /// </summary>
        public static string Please_write_the_email_you_want_to_add {
            get {
                return ResourceManager.GetString("Please_write_the_email_you_want_to_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productivity / Performance Ratio.
        /// </summary>
        public static string Productivity {
            get {
                return ResourceManager.GetString("Productivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profitability Ratio.
        /// </summary>
        public static string Profitability_Ratio {
            get {
                return ResourceManager.GetString("Profitability_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project identity.
        /// </summary>
        public static string Project_Identity {
            get {
                return ResourceManager.GetString("Project_Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner.
        /// </summary>
        public static string Project_Owner {
            get {
                return ResourceManager.GetString("Project_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects left.
        /// </summary>
        public static string Projects_left {
            get {
                return ResourceManager.GetString("Projects_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchased Profitability.
        /// </summary>
        public static string Purchased_Profitability {
            get {
                return ResourceManager.GetString("Purchased_Profitability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirecting....
        /// </summary>
        public static string RedirectMessage {
            get {
                return ResourceManager.GetString("RedirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email address to activate your account !.
        /// </summary>
        public static string Register_Success {
            get {
                return ResourceManager.GetString("Register_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered User.
        /// </summary>
        public static string Registered_User {
            get {
                return ResourceManager.GetString("Registered_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind me with Email.
        /// </summary>
        public static string Remind_me_with_Email {
            get {
                return ResourceManager.GetString("Remind_me_with_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales figures.
        /// </summary>
        public static string Sales_Figures {
            get {
                return ResourceManager.GetString("Sales_Figures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Code.
        /// </summary>
        public static string Security_Code {
            get {
                return ResourceManager.GetString("Security_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        public static string See_More {
            get {
                return ResourceManager.GetString("See_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See_Project.
        /// </summary>
        public static string See_Project {
            get {
                return ResourceManager.GetString("See_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me News-feed.
        /// </summary>
        public static string Send_Me_News_feed {
            get {
                return ResourceManager.GetString("Send_Me_News_feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me Notifications.
        /// </summary>
        public static string Send_Me_Notifications {
            get {
                return ResourceManager.GetString("Send_Me_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string Send_Message {
            get {
                return ResourceManager.GetString("Send_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Password.
        /// </summary>
        public static string Send_Password {
            get {
                return ResourceManager.GetString("Send_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Report Request.
        /// </summary>
        public static string Send_Report_Request {
            get {
                return ResourceManager.GetString("Send_Report_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Smoke Test.
        /// </summary>
        public static string Send_Smoke_Test {
            get {
                return ResourceManager.GetString("Send_Smoke_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Picture.
        /// </summary>
        public static string Share_Picture {
            get {
                return ResourceManager.GetString("Share_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Video.
        /// </summary>
        public static string Share_Video {
            get {
                return ResourceManager.GetString("Share_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared your Post.
        /// </summary>
        public static string Shared_your_Post {
            get {
                return ResourceManager.GetString("Shared_your_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Costs.
        /// </summary>
        public static string Shopping_Costs {
            get {
                return ResourceManager.GetString("Shopping_Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string Short_Description {
            get {
                return ResourceManager.GetString("Short_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should continue while broadcast.
        /// </summary>
        public static string Should_continue_while_broadcast {
            get {
                return ResourceManager.GetString("Should_continue_while_broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Networking List.
        /// </summary>
        public static string Speed_Networking_List {
            get {
                return ResourceManager.GetString("Speed_Networking_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent Budgetary.
        /// </summary>
        public static string Spent_Budgetary {
            get {
                return ResourceManager.GetString("Spent_Budgetary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Launch.
        /// </summary>
        public static string Started_Launch {
            get {
                return ResourceManager.GetString("Started_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story sharing.
        /// </summary>
        public static string Story_Sharing {
            get {
                return ResourceManager.GetString("Story_Sharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team/Co-Founder.
        /// </summary>
        public static string Team_Co_Founder {
            get {
                return ResourceManager.GetString("Team_Co_Founder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Size.
        /// </summary>
        public static string Team_Size {
            get {
                return ResourceManager.GetString("Team_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Spent.
        /// </summary>
        public static string Time_Spent {
            get {
                return ResourceManager.GetString("Time_Spent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        public static string Time_Zone {
            get {
                return ResourceManager.GetString("Time_Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn to Idea.
        /// </summary>
        public static string Turn_to_Idea {
            get {
                return ResourceManager.GetString("Turn_to_Idea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agreement.
        /// </summary>
        public static string User_Agreement {
            get {
                return ResourceManager.GetString("User_Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user type!.
        /// </summary>
        public static string UserType_Validation {
            get {
                return ResourceManager.GetString("UserType_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value proposition.
        /// </summary>
        public static string Value_Proposition {
            get {
                return ResourceManager.GetString("Value_Proposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Ratio.
        /// </summary>
        public static string Value_Ratio {
            get {
                return ResourceManager.GetString("Value_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit frequency.
        /// </summary>
        public static string Visit_Frequency {
            get {
                return ResourceManager.GetString("Visit_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where he lives.
        /// </summary>
        public static string Where_he_lives {
            get {
                return ResourceManager.GetString("Where_he_lives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who should see it.
        /// </summary>
        public static string Who_should_see {
            get {
                return ResourceManager.GetString("Who_should_see", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment.
        /// </summary>
        public static string Your_appointment {
            get {
                return ResourceManager.GetString("Your_appointment", resourceCulture);
            }
        }
    }
}
